/****************************************************************************
**
** Metadata for USMCVB_COM generated by dumpcpp from type library
** USMCVB_COM.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_USMCVB_COM_NOINLINES
#include "usmcvb_com.h"

using namespace USMCVB_COM;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[49];
    char stringdata0[470];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 22, 0),
QT_MOC_LITERAL(1, 23, 11, 0),
QT_MOC_LITERAL(2, 35, 11, 0),
QT_MOC_LITERAL(3, 47, 9, 0),
QT_MOC_LITERAL(4, 57, 0, 0),
QT_MOC_LITERAL(5, 58, 4, 0),
QT_MOC_LITERAL(6, 63, 6, 0),
QT_MOC_LITERAL(7, 70, 4, 0),
QT_MOC_LITERAL(8, 75, 4, 0),
QT_MOC_LITERAL(9, 80, 15, 0),
QT_MOC_LITERAL(10, 96, 4, 0),
QT_MOC_LITERAL(11, 101, 6, 0),
QT_MOC_LITERAL(12, 108, 4, 0),
QT_MOC_LITERAL(13, 113, 4, 0),
QT_MOC_LITERAL(14, 118, 6, 0),
QT_MOC_LITERAL(15, 125, 3, 0),
QT_MOC_LITERAL(16, 129, 11, 0),
QT_MOC_LITERAL(17, 141, 7, 0),
QT_MOC_LITERAL(18, 149, 16, 0),
QT_MOC_LITERAL(19, 166, 14, 0),
QT_MOC_LITERAL(20, 181, 16, 0),
QT_MOC_LITERAL(21, 198, 8, 0),
QT_MOC_LITERAL(22, 207, 9, 0),
QT_MOC_LITERAL(23, 217, 7, 0),
QT_MOC_LITERAL(24, 225, 9, 0),
QT_MOC_LITERAL(25, 235, 5, 0),
QT_MOC_LITERAL(26, 241, 11, 0),
QT_MOC_LITERAL(27, 253, 6, 0),
QT_MOC_LITERAL(28, 260, 4, 0),
QT_MOC_LITERAL(29, 265, 7, 0),
QT_MOC_LITERAL(30, 273, 7, 0),
QT_MOC_LITERAL(31, 281, 7, 0),
QT_MOC_LITERAL(32, 289, 9, 0),
QT_MOC_LITERAL(33, 299, 9, 0),
QT_MOC_LITERAL(34, 309, 8, 0),
QT_MOC_LITERAL(35, 318, 8, 0),
QT_MOC_LITERAL(36, 327, 12, 0),
QT_MOC_LITERAL(37, 340, 12, 0),
QT_MOC_LITERAL(38, 353, 12, 0),
QT_MOC_LITERAL(39, 366, 14, 0),
QT_MOC_LITERAL(40, 381, 8, 0),
QT_MOC_LITERAL(41, 390, 7, 0),
QT_MOC_LITERAL(42, 398, 3, 0),
QT_MOC_LITERAL(43, 402, 4, 0),
QT_MOC_LITERAL(44, 407, 10, 0),
QT_MOC_LITERAL(45, 418, 8, 0),
QT_MOC_LITERAL(46, 427, 9, 0),
QT_MOC_LITERAL(47, 437, 23, 0),
QT_MOC_LITERAL(48, 461, 7, 0)
    },
    "USMCVB_COM::USMCVB_COM\0Interface 1\0_USMCVB_COM\0exception\0\0code\0source\0disc\0"
    "help\0propertyChanged\0name\0signal\0argc\0argv\0Equals\0obj\0GetHashCode\0GetType\0"
    "mscorlib::_Type*\0PrintLastError\0PrintLastError_2\0QString&\0strErrMsg\0connect\0"
    "connect_2\0bool&\0blConnected\0curPos\0int&\0iCurPos\0getMode\0strMode\0getParams\0"
    "strParams\0getState\0strState\0isPoweredOff\0blIsPowerOff\0motorRunning\0blMotorRunning\0"
    "powerOff\0powerOn\0run\0dest\0stopMotion\0ToString\0connected\0USMCVB_COM::_USMCVB_COM\0"
    "control\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_USMCVB_COM__USMCVB_COM[] = {

 // content:
    7, // revision
    0,  // classname
    1, 14, // classinfo
    20, 16, // methods
    2, 174, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 

// signal: name, argc, parameters, tag, flags
    3, 4, 116, 4, 5,
    9, 1, 125, 4, 5,
    11, 3, 128, 4, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 135, 4, 9,
    16, 0, 138, 4, 9,
    17, 0, 139, 4, 9,
    19, 0, 140, 4, 9,
    20, 1, 141, 4, 9,
    23, 0, 144, 4, 9,
    24, 2, 145, 4, 9,
    27, 1, 150, 4, 9,
    30, 1, 153, 4, 9,
    32, 1, 156, 4, 9,
    34, 1, 159, 4, 9,
    36, 1, 162, 4, 9,
    38, 1, 165, 4, 9,
    40, 0, 168, 4, 9,
    41, 0, 169, 4, 9,
    42, 1, 170, 4, 9,
    44, 0, 173, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Bool, QMetaType::QVariant, 15,
    QMetaType::Int,
    0x80000000 | 18,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 21, 22,
    QMetaType::Bool,
    QMetaType::Int, 0x80000000 | 21, 0x80000000 | 25, 22, 26,
    QMetaType::Int, 0x80000000 | 28, 29,
    QMetaType::Int, 0x80000000 | 21, 31,
    QMetaType::Int, 0x80000000 | 21, 33,
    QMetaType::Int, 0x80000000 | 21, 35,
    QMetaType::Int, 0x80000000 | 25, 37,
    QMetaType::Int, 0x80000000 | 25, 39,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 43,
    QMetaType::Int,

 // properties: name, type, flags
    45, QMetaType::QString, 0x0a005001, 		 // QString ToString
    46, QMetaType::Bool, 0x01005001, 		 // bool connected

    0 // eod
};

const QMetaObject USMCVB_COM::USMCVB_COM::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_USMCVB_COM__USMCVB_COM, 0, 0, 0 }
};

void *USMCVB_COM::USMCVB_COM::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "USMCVB_COM::USMCVB_COM"))
        return static_cast<void*>(const_cast<USMCVB_COM*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_USMCVB_COM___USMCVB_COM[] = {

 // content:
    7, // revision
    47,  // classname
    0, 0, // classinfo
    17, 14, // methods
    2, 152, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    3, 4, 99, 4, 5,
    9, 1, 108, 4, 5,
    11, 3, 111, 4, 5,

// slot: name, argc, parameters, tag, flags
    19, 0, 118, 4, 9,
    20, 1, 119, 4, 9,
    23, 0, 122, 4, 9,
    24, 2, 123, 4, 9,
    27, 1, 128, 4, 9,
    30, 1, 131, 4, 9,
    32, 1, 134, 4, 9,
    34, 1, 137, 4, 9,
    36, 1, 140, 4, 9,
    38, 1, 143, 4, 9,
    40, 0, 146, 4, 9,
    41, 0, 147, 4, 9,
    42, 1, 148, 4, 9,
    44, 0, 151, 4, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 21, 22,
    QMetaType::Bool,
    QMetaType::Int, 0x80000000 | 21, 0x80000000 | 25, 22, 26,
    QMetaType::Int, 0x80000000 | 28, 29,
    QMetaType::Int, 0x80000000 | 21, 31,
    QMetaType::Int, 0x80000000 | 21, 33,
    QMetaType::Int, 0x80000000 | 21, 35,
    QMetaType::Int, 0x80000000 | 25, 37,
    QMetaType::Int, 0x80000000 | 25, 39,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, 43,
    QMetaType::Int,

 // properties: name, type, flags
    46, QMetaType::Bool, 0x01005001, 		 // bool connected
    48, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _USMCVB_COM::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_USMCVB_COM___USMCVB_COM, 0, 0, 0 }
};

void *_USMCVB_COM::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "USMCVB_COM::_USMCVB_COM"))
        return static_cast<void*>(const_cast<_USMCVB_COM*>(this));
    return QAxObject::qt_metacast(_clname);
}

