/****************************************************************************
**
** Namespace USMCVB_COM generated by dumpcpp from type library
** USMCVB_COM.tlb
**
****************************************************************************/

#ifndef QAX_DUMPCPP_USMCVB_COM_H
#define QAX_DUMPCPP_USMCVB_COM_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef USMCVB_COM_EXPORT
#define USMCVB_COM_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace
namespace mscorlib {
    class _Type;
}


namespace USMCVB_COM {


class USMCVB_COM_EXPORT _USMCVB_COM : public QAxObject
{
public:
    _USMCVB_COM(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property connected
    */
    inline bool connected() const; //Returns the value of connected

    /*
    Method PrintLastError
    */
    inline void PrintLastError();

    /*
    Method PrintLastError_2
    */
    inline void PrintLastError_2(QString& strErrMsg);

    /*
    Method connect
    */
    inline bool connect();

    /*
    Method connect_2
    */
    inline int connect_2(QString& strErrMsg, bool& blConnected);

    /*
    Method curPos
    */
    inline int curPos(int& iCurPos);

    /*
    Method getMode
    */
    inline int getMode(QString& strMode);

    /*
    Method getParams
    */
    inline int getParams(QString& strParams);

    /*
    Method getState
    */
    inline int getState(QString& strState);

    /*
    Method isPoweredOff
    */
    inline int isPoweredOff(bool& blIsPowerOff);

    /*
    Method motorRunning
    */
    inline int motorRunning(bool& blMotorRunning);

    /*
    Method powerOff
    */
    inline int powerOff();

    /*
    Method powerOn
    */
    inline int powerOn();

    /*
    Method run
    */
    inline int run(int dest);

    /*
    Method stopMotion
    */
    inline int stopMotion();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class USMCVB_COM_EXPORT USMCVB_COM : public QAxObject
{
public:
    USMCVB_COM(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl("{e5622ecd-cc13-48c9-9bd4-f736ed1c0785}");
    }

    USMCVB_COM(_USMCVB_COM *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property ToString
    */
    inline QString ToString() const; //Returns the value of ToString

    /*
    Property connected
    */
    inline bool connected() const; //Returns the value of connected

    /*
    Method Equals
    */
    inline bool Equals(const QVariant& obj);

    /*
    Method GetHashCode
    */
    inline int GetHashCode();

    /*
    Method GetType
    */
    inline mscorlib::_Type* GetType();

    /*
    Method PrintLastError
    */
    inline void PrintLastError();

    /*
    Method PrintLastError_2
    */
    inline void PrintLastError_2(QString& strErrMsg);

    /*
    Method connect
    */
    inline bool connect();

    /*
    Method connect_2
    */
    inline int connect_2(QString& strErrMsg, bool& blConnected);

    /*
    Method curPos
    */
    inline int curPos(int& iCurPos);

    /*
    Method getMode
    */
    inline int getMode(QString& strMode);

    /*
    Method getParams
    */
    inline int getParams(QString& strParams);

    /*
    Method getState
    */
    inline int getState(QString& strState);

    /*
    Method isPoweredOff
    */
    inline int isPoweredOff(bool& blIsPowerOff);

    /*
    Method motorRunning
    */
    inline int motorRunning(bool& blMotorRunning);

    /*
    Method powerOff
    */
    inline int powerOff();

    /*
    Method powerOn
    */
    inline int powerOn();

    /*
    Method run
    */
    inline int run(int dest);

    /*
    Method stopMotion
    */
    inline int stopMotion();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_USMCVB_COM_NOINLINES
inline QString USMCVB_COM::ToString() const
{
    QVariant qax_result = property("ToString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline bool USMCVB_COM::connected() const
{
    QVariant qax_result = property("connected");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline bool USMCVB_COM::Equals(const QVariant& obj)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&obj};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int USMCVB_COM::GetHashCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline mscorlib::_Type* USMCVB_COM::GetType()
{
    mscorlib::_Type* qax_result = 0;
#ifdef QAX_DUMPCPP_MSCORLIB_H
    qRegisterMetaType<mscorlib::_Type*>("mscorlib::_Type*", &qax_result);
    qRegisterMetaType<mscorlib::_Type>("mscorlib::_Type", qax_result);
#endif
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline void USMCVB_COM::PrintLastError()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void USMCVB_COM::PrintLastError_2(QString& strErrMsg)
{
    void *_a[] = {0, (void*)&strErrMsg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline bool USMCVB_COM::connect()
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int USMCVB_COM::connect_2(QString& strErrMsg, bool& blConnected)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strErrMsg, (void*)&blConnected};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int USMCVB_COM::curPos(int& iCurPos)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&iCurPos};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline int USMCVB_COM::getMode(QString& strMode)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strMode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int USMCVB_COM::getParams(QString& strParams)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strParams};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int USMCVB_COM::getState(QString& strState)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strState};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int USMCVB_COM::isPoweredOff(bool& blIsPowerOff)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&blIsPowerOff};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int USMCVB_COM::motorRunning(bool& blMotorRunning)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&blMotorRunning};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int USMCVB_COM::powerOff()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline int USMCVB_COM::powerOn()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline int USMCVB_COM::run(int dest)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&dest};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline int USMCVB_COM::stopMotion()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}


inline bool _USMCVB_COM::connected() const
{
    QVariant qax_result = property("connected");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline void _USMCVB_COM::PrintLastError()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void _USMCVB_COM::PrintLastError_2(QString& strErrMsg)
{
    void *_a[] = {0, (void*)&strErrMsg};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline bool _USMCVB_COM::connect()
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline int _USMCVB_COM::connect_2(QString& strErrMsg, bool& blConnected)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strErrMsg, (void*)&blConnected};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline int _USMCVB_COM::curPos(int& iCurPos)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&iCurPos};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline int _USMCVB_COM::getMode(QString& strMode)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strMode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int _USMCVB_COM::getParams(QString& strParams)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strParams};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int _USMCVB_COM::getState(QString& strState)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&strState};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline int _USMCVB_COM::isPoweredOff(bool& blIsPowerOff)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&blIsPowerOff};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int _USMCVB_COM::motorRunning(bool& blMotorRunning)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&blMotorRunning};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int _USMCVB_COM::powerOff()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int _USMCVB_COM::powerOn()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int _USMCVB_COM::run(int dest)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&dest};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int _USMCVB_COM::stopMotion()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<USMCVB_COM::USMCVB_COM, /* Accepted */ true> {
    static void Delete(void *t) { delete static_cast<USMCVB_COM::USMCVB_COM*>(t); }
    static void *Create(const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new USMCVB_COM::USMCVB_COM();
    }
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<USMCVB_COM::USMCVB_COM*>(t)->USMCVB_COM::USMCVB_COM::~USMCVB_COM();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) USMCVB_COM::USMCVB_COM;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const USMCVB_COM::USMCVB_COM*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<USMCVB_COM::USMCVB_COM*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<USMCVB_COM::_USMCVB_COM, /* Accepted */ true> {
    static void Delete(void *t) { delete static_cast<USMCVB_COM::_USMCVB_COM*>(t); }
    static void *Create(const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new USMCVB_COM::_USMCVB_COM();
    }
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<USMCVB_COM::_USMCVB_COM*>(t)->USMCVB_COM::_USMCVB_COM::~_USMCVB_COM();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) USMCVB_COM::_USMCVB_COM;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const USMCVB_COM::_USMCVB_COM*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<USMCVB_COM::_USMCVB_COM*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

